
package com.kfh.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CourseServiceImplService", targetNamespace = "http://service.kfh.com/", wsdlLocation = "http://localhost:9090/ws/course?wsdl")
public class CourseServiceImplService
    extends Service
{

    private final static URL COURSESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COURSESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName COURSESERVICEIMPLSERVICE_QNAME = new QName("http://service.kfh.com/", "CourseServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/ws/course?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COURSESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        COURSESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CourseServiceImplService() {
        super(__getWsdlLocation(), COURSESERVICEIMPLSERVICE_QNAME);
    }

    public CourseServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COURSESERVICEIMPLSERVICE_QNAME, features);
    }

    public CourseServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, COURSESERVICEIMPLSERVICE_QNAME);
    }

    public CourseServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COURSESERVICEIMPLSERVICE_QNAME, features);
    }

    public CourseServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourseServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CourseService
     */
    @WebEndpoint(name = "CourseServiceImplPort")
    public CourseService getCourseServiceImplPort() {
        return super.getPort(new QName("http://service.kfh.com/", "CourseServiceImplPort"), CourseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourseService
     */
    @WebEndpoint(name = "CourseServiceImplPort")
    public CourseService getCourseServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.kfh.com/", "CourseServiceImplPort"), CourseService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COURSESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw COURSESERVICEIMPLSERVICE_EXCEPTION;
        }
        return COURSESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
