
package com.kfh.client;

import java.util.List;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CourseService", targetNamespace = "http://service.kfh.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CourseService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addCourse", targetNamespace = "http://service.kfh.com/", className = "com.kfh.client.AddCourse")
    @ResponseWrapper(localName = "addCourseResponse", targetNamespace = "http://service.kfh.com/", className = "com.kfh.client.AddCourseResponse")
    @Action(input = "http://service.kfh.com/CourseService/addCourseRequest", output = "http://service.kfh.com/CourseService/addCourseResponse")
    public void addCourse(
        @WebParam(name = "arg0", targetNamespace = "")
        Course arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.kfh.client.Course>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCourses", targetNamespace = "http://service.kfh.com/", className = "com.kfh.client.GetAllCourses")
    @ResponseWrapper(localName = "getAllCoursesResponse", targetNamespace = "http://service.kfh.com/", className = "com.kfh.client.GetAllCoursesResponse")
    @Action(input = "http://service.kfh.com/CourseService/getAllCoursesRequest", output = "http://service.kfh.com/CourseService/getAllCoursesResponse")
    public List<Course> getAllCourses();

}
